from abc import ABC, abstractmethod

class RepositorioResenas(ABC):
    @abstractmethod
    def crear(self, datos: dict) -> dict: ...
    @abstractmethod
    def obtener_por_id(self, id: int) -> dict | None: ...
    @abstractmethod
    def listar_todos(self) -> list[dict]: ...
    @abstractmethod
    def actualizar(self, id: int, datos: dict) -> dict | None: ...
    @abstractmethod
    def eliminar(self, id: int) -> bool: ...
    @abstractmethod
    def buscar(self, filtros: dict) -> list[dict]: ...
    @abstractmethod
    def paginar(self, pagina: int, por_pagina: int) -> dict: ...
    @abstractmethod
    def exportar_csv(self) -> str: ...
    @abstractmethod
    def importar_csv(self, contenido: str) -> int: ...
    @abstractmethod
    def archivar(self, id: int) -> bool: ...
    @abstractmethod
    def obtener_historial(self, id: int) -> list[dict]: ...


class RepositorioResenasSoloLectura(RepositorioResenas):
    """Repositorio de consulta para el panel público — no puede crear ni eliminar."""
    def crear(self, datos): raise NotImplementedError        # ← forzado
    def actualizar(self, id, datos): raise NotImplementedError
    def eliminar(self, id): raise NotImplementedError
    def importar_csv(self, contenido): raise NotImplementedError
    def archivar(self, id): raise NotImplementedError
    def obtener_historial(self, id): raise NotImplementedError
    # Solo implementa realmente:
    def obtener_por_id(self, id): ...
    def listar_todos(self): ...
    def buscar(self, filtros): ...
    def paginar(self, pagina, por_pagina): ...
    def exportar_csv(self): ...